# Generated by Django 5.0.6 on 2024-06-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-date_posted',), 'verbose_name_plural': 'Posts'},
        ),
    ]
