# Generated by Django 5.0.6 on 2024-06-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-date_posted',), 'permissions': [('can_create_post', 'Can create post')], 'verbose_name_plural': 'Posts'},
        ),
    ]
